### ISSUE TITLE
kubectl exec tty issue through the wrapper

### ISSUE THREAD

**Issue by redsux** [little-angry-clouds/kubernetes-binaries-managers#13]
Hi,

I've an issue with the wrapper when trying to open a pseudo tty on `kubectl exec -it` commands = it responds `Unable to use a TTY`.

Environment :
- CentOS 8
- Kubectl v1.15.10

Issue :
```bash
$> kubectl -n NS-NAME exec -it POD-NAME -c CONTAINER-NAME -- /bin/sh`
Unable to use a TTY - input is not a terminal or the right kind of file
```

Workaround :
```bash
$> ~/.bin/kubectl-v1.15.10 -n NS-NAME exec -it POD-NAME -c CONTAINER-NAME -- /bin/sh
/ #
```

**Comment by alexppg** [comment]
@redsux Hey, I've already addressed this issue in in this PR https://github.com/little-angry-clouds/kubernetes-binaries-managers/pull/9. Which version are you using?

**Comment by alexppg** [comment]
I'll just close the issue assuming it's all working as expected. Feel free to reopen if that's not the case!

**Comment by redsux** [comment]
Sorry for the delay, seems I forgot to update "kubectl-wrapper" when updating "kbenv" !
Thanks for the fix and sorry for this useless issue.

**Comment by alexppg** [comment]
No problem, the effort is appreciated. It also made explain what kind of errors you can find when using the list remote functionality, so thanks!
