### ISSUE TITLE
helmenv : error when trying to run helm

### ISSUE THREAD

**Issue by Pea13** [little-angry-clouds/kubernetes-binaries-managers#19]
Hello,

I have downloaded the latest version of helmenv. I have followed the README to do the installation and i have installed 2 differents versions of helm :
```
% helmenv list local
3.3.4
3.3.3

```

But when i try to run helm:
```
% helm
fork/exec /home/pea/.bin/helm-vauto: no such file or directory
```

Any ideas ?
Regards,

**Comment by Pea13** [comment]
I can fix this error if i create a .helm_version file
```
% echo 3.3.3 > .helm_version
% helm version
version.BuildInfo{Version:"v3.3.3", GitCommit:"55e3ca022e40fe200fbc855938995f40b2a68ce0", GitTreeState:"clean", GoVersion:"go1.14.9"}
```

**Comment by alexppg** [comment]
@Pea13 It sounds like you still have to set the version with `helmenv use 3.3.4`. May you try it?

**Comment by Pea13** [comment]
You're right ! Thank you for the tips !
Regards,
