### ISSUE TITLE
helmenv does not propagate exit code

### ISSUE THREAD

**Issue by trecloux** [little-angry-clouds/kubernetes-binaries-managers#23]
Some tools or scripts (ex: skaffold) depend on helm exit code for their workflow.

It looks like helmenv does not propagate helm exit code but prints it instead.
```
exit status 1
```

**Comment by alexppg** [comment]
Thanks for reporting this issue! It should be fixed by now. The release is been created at the moment, so it shouldn't take long.

**Comment by alexppg** [comment]
Done. Let me know if it does not fix your issue.

**Comment by trecloux** [comment]
Hi @alexppg, thanks for the amazingly quick fix and release.

It fixes with issue, :+1:
