### ISSUE TITLE
Unable to install v2.17.0

### ISSUE THREAD

**Issue by dking6902** [little-angry-clouds/kubernetes-binaries-managers#35]
Hi I am unable to install v2.17.0

```helm list-remotes``` shows the version I need, however when I run the helm install command I get the following.

```
helmenv install v2.17.0      
Downloading binary...
There was a problem downloading the file! You probably typed the version incorrectly, but it may be something else.```

**Comment by alexppg** [comment]
Hi!

Just to be sure, you're using the Go version (which is the one on this repo) of the program not the bash one, do you? The bash one got deprecated.

The command to list with the Go version is `helmenv list remote`. This will return you the versions without the `v` prefix, so to install would be `helmenv install 2.17.0`.

Let me know if it works for you.

**Comment by alexppg** [comment]
I'll close it for now, feel free to reopen it if the problem persists.
