### ISSUE TITLE
Getting "unknown command" when open new terminal

### ISSUE THREAD

**Issue by brunowego** [little-angry-clouds/kubernetes-binaries-managers#36]
Currently, when I open a new terminal, I'm getting the follow message:

```sh
Error: unknown command "failed" for "kbenv"
Run 'kbenv --help' for usage.
unknown command "failed" for "kbenv"
```

Any idea how avoid it? Thanks!

**Comment by alexppg** [comment]
Hello there!
That's weird. Do you have any invocation to kbenv on your shell conbfiguration? (bashrc, zshrc, ..) It shouldn't do anything automatically, the installations methods only install the tools, they don't configure the shell for anything.

**Comment by brunowego** [comment]
@alexppg not happened again. I will close, if happen again, I will investigate to come here with more information. Thanks!
