### ISSUE TITLE
kbenv use auto not working with AWS EKS

### ISSUE THREAD

**Issue by EHJ-52n** [little-angry-clouds/kubernetes-binaries-managers#45]
The AWS EKS k8s version postfix results in not working kbenv use auto:

```shell
~ kbenv version    
Commit: d5e1e2075e88bf4f791749cc06ae02f82fb8a710
Date: "2022-05-20T12:20:19Z"
Version: 1.0.0
~ kubectl version                                                                                                    
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.17", GitCommit:"953be8927218ec8067e1af2641e540238ffd7576", GitTreeState:"clean", BuildDate:"2023-02-22T13:34:27Z", GoVersion:"go1.19.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23+", GitVersion:"v1.23.17-eks-a5565ad", GitCommit:"23f44c7dd4e8e23856387345e7cb80bf0f93ced6", GitTreeState:"clean", BuildDate:"2023-06-15T21:19:39Z", GoVersion:"go1.19.6", Compiler:"gc", Platform:"linux/amd64"}
~ kbenv use auto   
Done! Using auto version.
~ kubectl version
fork/exec /home/eike/.bin/kubectl-v1.23.17-eks-a5565ad: no such file or directory
```

The postfix `-eks-a5565ad` MUST be removed when parsing the server's `GitVersion` to identify the binary version to use.

**Comment by creeder-uturn** [comment]
I think this is a duplicate of https://github.com/little-angry-clouds/kubernetes-binaries-managers/issues/37

There is a PR https://github.com/little-angry-clouds/kubernetes-binaries-managers/pull/38 to fix it, as well

**Comment by EHJ-52n** [comment]
Thank you for establishing the link between these two issues and pointing to the PR.

The project itself seems to be abandoned.

Do you know any working fork?

**Comment by creeder-uturn** [comment]
@EHJ-52n unfortunately, I do not. I personally just installed the newest version as I have no very old clusters to manage and I haven't run into any version imcompatibilities even if outside of the window. Hopefully this gets re-maintained soon :)
